#!/bin/bash
# script file for pa

javac -classpath /home/tky/algs4:. ./Board.java
# java -classpath /home/tky/algs4:. Board puzzle19.txt puzzle19.txt

javac -classpath /home/tky/algs4:. ./Solver.java
java -classpath /home/tky/algs4:. Solver puzzle19.txt

zip 8puzzle.zip Board.java Solver.java
