#!/bin/bash
# script file for hw1

javac  -classpath /home/tky/algs4:. ./Percolation.java
java -classpath /home/tky/algs4:. Percolation

javac  -classpath /home/tky/algs4:. ./PercolationStats.java
java  -classpath /home/tky/algs4:. PercolationStats
