#!/bin/bash
# script file for pa

javac -classpath /home/tky/algs4:. ./Point.java
# java -classpath /home/tky/algs4:. Point

javac -classpath /home/tky/algs4:. ./LineSegment.java

javac -classpath /home/tky/algs4:. ./BruteCollinearPoints.java
java -classpath /home/tky/algs4:. BruteCollinearPoints ./input8.txt
