#!/bin/bash
# script file for pa

javac -classpath /home/tky/algs4:. ./Edge.java
javac -classpath /home/tky/algs4:. ./EdgeWeightedGraph.java
javac -classpath /home/tky/algs4:. ./PrimMST.java
javac -classpath /home/tky/algs4:. ./KruskalMST.java

javac -classpath /home/tky/algs4:. ./DirectedEdge.java
javac -classpath /home/tky/algs4:. ./EdgeWeightedDigraph.java
java -classpath /home/tky/algs4:. ./EdgeWeightedDigraph.java ./tinyEWD.txt

