#!/bin/bash
# script file for pa

javac -classpath /home/tky/algs4:. ./WordNet.java

javac -classpath /home/tky/algs4:. ./SAP.java
#java -classpath /home/tky/algs4:. SAP digraph-wordnet.txt

javac -classpath /home/tky/algs4:. ./Outcast.java
#java -classpath /home/tky/algs4:. Outcast synsets.txt hypernyms.txt outcast5.txt outcast8.txt outcast11.txt

#java -classpath /home/tky/algs4:. WordNet
zip wordnet.zip WordNet.java SAP.java Outcast.java



